var fs = require('fs');

// run with `node Generators/sumFeatureGen.js`;

var additionFeature = {
    name: 'Addition',
    scenarios: [
        {
            name: "Add two numbers",
            data: [
                [0,0],
                [1,0],
                [1,1],
                [2,3]
            ]
        }
    ]
}

// Feature: Addition
//     Scenario: Add two numbers
//         Given the numbers 1 and 3
//         When they are added together
//         Then the result should be 4


function createFeatureFromData(fObj) {
    var fText = "# This file was generated by a function in Generators/sumFeatureGen.js\n\n"

    fText += 'Feature: ' + fObj.name + '\n';

    fObj.scenarios.forEach(function(scen){

        fText += "\tScenario: " + scen.name + "\n";

        scen.data.forEach(function(nums){
            fText += "\t\tGiven the numbers " + nums[0] + " and " + nums[1] + "\n";
            fText += "\t\tWhen they are added together\n"
            fText += "\t\tThen the result should be " + Number(nums[0] + nums[1]) + "\n\n"
        })
    })
    
    fs.writeFile(
        "features/add_generated.feature", 
        fText, 
        (err) => {
            if (err) throw err;
            console.log('The add_generated.feature file has been saved!');
        }
    );
}

createFeatureFromData(additionFeature);

