# This files was generated by a function in Generators/sumFeatureGen.js

Feature: Addition
	Scenario: Add two numbers
		Given the numbers 0 and 0
		When they are added together
		Then the result should be 0

		Given the numbers 1 and 0
		When they are added together
		Then the result should be 1

		Given the numbers 1 and 1
		When they are added together
		Then the result should be 2

		Given the numbers 2 and 3
		When they are added together
		Then the result should be 5