# This file was generated by a function in Generators/productRestrictionGen.js

Feature: Restrict products by company
	Scenario Outline: Users can only order products that belong to their own company.
		Given a user has an open order on codebase version 2
		And the user has a company id of <userCompanyId>
		When a user adds a product with <productCompanyId> to their cart
		Then the alert message should be <message>
		Examples:
			| userCompanyId | productCompanyId | message                                                         |
			| 1             | 1                | 'Item added to cart!'                                           |
			| 1             | 2                | 'Sorry. You can only add items from your company to your cart.' |
			| 1             | 1                | 'Item added to cart!'                                           |
			| 1             | 1                | 'Item added to cart!'                                           |
			| 2             | 1                | 'Sorry. You can only add items from your company to your cart.' |
