# This file was generated by a function in Generators/productRestrictionGen.js

	Scenario: If either company or order have codebase version 1 allow users to order products that belong to any company.
		Given an order is placed on codebase version 1 or a company is on version 1
		When a user puts a product in their cart that is from another company
		Then the item is allowed and they should see the 'item successfully added' message.
